version: '3' #docker-composeのバージョンを指定
services:
    db:
        image: mysql:5.7 #mysql5.7が準備されているimageを指定
        environment:
            - MYSQL_ROOT_PASSWORD=secret #rootのパスワード
            - MYSQL_DATABASE=revel #revelデータベースの作成
            - MYSQL_USER=revel #revelユーザの作成
            - MYSQL_PASSWORD=secret #revelユーザのパスワード
    web:
        build: . #Dockerfileをビルド
        command: revel run revel-docker #docker-compose up の際にアプリケーション実行
        volumes:
            - ./:/go/src/revel-docker #作成したフォルダにアプリケーションをマウント
        ports:
            - 9001:9001
        depends_on:
            - db #dbとつなげる
